### ISSUE TITLE
Unable to assign action to choice nodes?

### ISSUE THREAD

**Issue by atownley** [jcoglan/canopy#12]
Hi,

It seems like the following doesn't parse in the meta grammar:

```
rule1 <- option1 / option2 %my_action

option1 <- "one"

option2 <- "two"
```

Is this by design or by accident? ;)

I looked at the parser code, but since I've only started looking at it today, I'm not really confident I understand it yet.

Cheers,

ast

**Comment by jcoglan** [comment]
It's by design. Action code is supposed to *replace* Canopy's own built-in default node construction code, to save time and memory while parsing. It only makes sense to do this on rules that actually construct new nodes.

So, things like choices, or optional (`?`) nodes, don't apply -- they just delegate to some other expression and return whatever node is generated there, rather than constructing new nodes themselves.

If you want an action to apply to a choice, you need to apply it to all branches of the choice.

```
rule1 <- option1 %my_action / option2 %my_action
```

Or, you can use type annotations, with parens because of precedence rules:

```
rule1 <- (option1 / option2) <MyType>

**Comment by jcoglan** [comment]
Can I close this issue, or did you have more questions in response to what I posted?

**Comment by atownley** [comment]
No, that's fine.  Funnily enough, I've started using this again about last week or so, and making better progress with it this time around.  I'd remembered what you'd said, so while I'm not thrilled that it doesn't apply the same as the type annotations, I'm ok with it as long as it's documented.

Closing the issue.

Cheers,

ast
