### ISSUE TITLE
Project status / roadmap

### ISSUE THREAD

**Issue by mindplay-dk** [jcoglan/canopy#14]
What's the status of this project?

There has been no release and almost no commits since July 2015 - is that because it's "done" (e.g. feature-complete and working) or because you abandoned it?

I'm looking at this as an alternative to PEG.js, which I dislike because of the hard coupling to JS and inline JS statements - what you're doing makes more sense to me, and the project appears to be fairly complete?

If so, perhaps consider tagging a 1.0 release?

Also, have you benchmarked this? e.g. your JSON parser vs PEG.js's JSON parser? It's really important to have some idea about how something like this performs before committing to it.

I'm thinking about building a simple language workbench for this, a bit like the one PEG.js has, but maybe with the addition of pass/fail test-cases, along the lines of regex101.com.

For the record, I don't really know what I'm doing, I'm still pretty new to parsers in general - have been playing with PEG.js and PetitParser (which I ported to PHP and partially to JS as well) and also experimented with my own implementation of a parser combinator library. I really like the idea of combinators and skipping the compile-step, but they appear to perform horribly, so now I'm interested in this :-)

**Comment by mindplay-dk** [comment]
Oh, I see you [do](https://github.com/jcoglan/canopy/blob/master/examples/javascript.js) have benchmarks in there :-)

Maybe consider posting the results on the web-site?

**Comment by jcoglan** [comment]
@mindplay-dk Apologies for taking a while to respond to this, it's been a busy year.

The project doesn't have a defined roadmap as such, it's a hobby project of mine and I work on it as and when I feel like it. It's picked up again recently because I've been using it a lot in other projects.

So essentially it's "done" in the sense it does everything I want of it right now, but that might change in future as I learn more about parsing.

As for benchmarks, I typically avoid publishing benchmarks even if I use them to check things while I work, because they're never representative. Performance will vary based on your grammars and inputs and people shouldn't be making decisions without comparing different tools on their own workloads, rather than relying on benchmarks from a few random examples.

**Comment by mindplay-dk** [comment]
If you feel like it's complete and stable, maybe consider tagging a release?

As for benchmarks, yeah, I understand and agree with everything you said, but I don't think there's anything misleading about posting them - I mostly like to see a benchmark to reassure myself that (for example) performance for a given grammer isn't *detrementally* slower compared with another framework. Performance does matter - in some cases it's even crucial. And this framework appears to perform well. If I were you, I would post the result, along with your disclaimer - that's honest, and at least gives someone an idea of what the performance can/might be like :-)

**Comment by jcoglan** [comment]
I will be publishing version 0.4 when the current train of work on refactoring the internals and adding a couple new features is one. Thanks a lot for your suggestions on benchmarks, I'll consider it when I'm updating the docs :)
