### ISSUE TITLE
Is it possible to match more general regular expressions?

### ISSUE THREAD

**Issue by vsajip** [jcoglan/canopy#25]
Is there any support for more generic regular expressions than the ones mentioned in the documentation? For example,
```
EOL <- \s*((#[^\f\r\n]*)?[\f\r\n])\s*
```
might be used to parse end-of-lines with optional comments following a `#` character, or
```
FLOAT <- (\.[0-9]+|[0-9]+\.[0-9]*)([Ee]-?[0-9]+)?
```
might be used to parse floating-point numbers.

**Comment by jcoglan** [comment]
This is not possible. Embedding regex within Canopy would either require Canopy itself to implement a regex parser and interpreter for each backend, or delegate regex handling to the target language. Both of these pose a lot of implementation problems, and the latter would also preclude Canopy from being able to do various automatic grammar transformations, since it would essentially entail an opaque embedded language that could not be reasoned about.

Canopy itself should be able parse any regular language without resorting to regexes, and I often reach for it for parsing regular languages just to makes things more readable than writing regexes.

**Comment by vsajip** [comment]
OK, thanks for the feedback.
