### ISSUE TITLE
Feasibility of agumenting actions with enter/exit functions for each node

### ISSUE THREAD

**Issue by realisation** [jcoglan/canopy#29]
It would be great if, like in a visitor for babeljs, there was an option to write an enter/exit function for each node. I wonder if that'd be a simple matter or a complicated affair to implement. 

My first thought is that it wouldn't be able to do it directly as it traverses the tree because PEG works by matching all the way to the end of the present rule, thereby returning the parsed result starting at the deepest node.
 
But I wonder how difficult it would be to retain the tree after parse and then apply a depth first traversal of actions in a manner similar to babel. 

And as a side note, I wonder if an api similar to babel's path api would map onto a traversal process like that.

**Comment by jcoglan** [comment]
This sounds like it's out of scope for Canopy. The feature you're referring to in Babel traverses the tree _after_ parsing is completed, not during it. During this during parsing would be wasteful and produce confusing results, because many of the rules you enter will end up failing and not be part of the final parse.

The best way to do this is to implement a traversal over the tree yourself _after_ Canopy returns it to you.
