### ISSUE TITLE
Make the package web-friendly

### ISSUE THREAD

**Issue by mindplay-dk** [jcoglan/canopy#58]
Just out of boredom, I started building a [playground](https://codesandbox.io/s/canopy-9bo3kj?file=/src/index.js) for Canopy.

Unfortunately, the package isn't "web friendly", so it's not really possible at this time.

The trouble is the `Base` class, which is hard coded with dependencies on NodeJS's `fs` and `path` - ideally, a package shouldn't have dependencies on NodeJS. (or any specific JS environment, if possible.)

Some ways around this dependency:

1. Convert templates to `.js` and `require` them (a bit clumsy to maintain because of `\` escapes.)
2. Convert templates to `.js` at build-time (but you don't currently have any `scripts` in `package.json`)
3. Introduce a compiler (Parcel or Rollup, etc.)

The templates are an implementation detail, so they probably should just be built-in?

You also might consider using modern string templates - this is kind of option 1, but this would enable you to get rid of the template engine dependency as well, and formalize the template arguments, which might be the simplest, most elegant solution.

So instead of templates like this:

```
if (typeof require === 'function' && typeof exports === 'object') {
  Object.assign(exports, exported);
} else {
  var ns = (typeof this === 'undefined') ? window : this;
{{#each namespace}}
  ns = ns.{{this}} = ns.{{this}} || {};
{{/each}}
  ns.{{name}} = exported;
}
```

Instead, you'd have an actual function, like this:

```js
module.exports = ({ name, namespaces }) => `
if (typeof require === 'function' && typeof exports === 'object') {
  Object.assign(exports, exported);
} else {
  var ns = (typeof this === 'undefined') ? window : this;
  ${namespaces
    .map(namespace => `ns = ns.{{namespace}} = ns.{{namespace}} || {};`)
    .join("\n  ")}
  ns.${name} = exported;
}
`
```

The templates, with extensions like `.js`, `.rb` and `.java` aren't valid code in the first place, because of the placeholders.

You could probably make these functions compute/return the filename as well - that way it's all neatly tugged away with no dependency on the file-system; only the CLI front-end would depend on the filesystem, which is appropriate, since that's specifically designated for Node only, while the library code would be free from any dependencies on more than the standard JS run-time.

Thoughts? 🙂

**Comment by jcoglan** [comment]
Hi @mindplay-dk, I don't know if you know this but the Canopy compiler did used to run in the browser. We decided to make it Node-only because this substantially simplified the build and test process, which was really holding us back from maintaining the code and publishing releases. There was very limited utility to having it run in the browser, especially once we added support for multiple languages, some of which require output split into multiple files.

We extracted the code that's now in templates _out_ of the JavaScript source code to make them easier to edit and maintain, and rolling them back into JS as their source form is not appealing. In theory we could pre-compile the templates into JS modules, and then bundle the `lib` code using Webpack or similar. However this reintroduces a build step we put a lot of effort into removing for 0.4, and requires adding a build step and browser support to our CI pipeline, which is a lot of additional complexity.

We are planning to add features that will further rely on the filesystem, for example allowing grammars to import one another. This will only make supporting browser-based use even harder, and I'm really reluctant to make an already tricky-to-build project even more complicated to support a non-production use case.

**Comment by mindplay-dk** [comment]
That's too bad.

I think something like [this](https://chevrotain.io/playground/) would provide a lot of utility - and I could see expanding this into a full grown language workbench of sorts, e.g. with the ability to add test-cases, visualize parse trees, etc.

What if the build step was fast and added very little complexity? I recently switched by side project to Parcel 2.0, and it requires literally nothing more than a `main` field and a `parcel build` command - no configuration files or anything of that sort.

> We are planning to add features that will further rely on the filesystem, for example allowing grammars to import one another.

This doesn't need to involve the file system - you already have logical filenames as part of your output model, so just make the CLI add the files to an input model as `{name, content}` pairs.

Keeping the filesystem out of the equation would support faster and simpler testing as well.

Practically every other JS based language tool [runs on the web](https://chevrotain.io/performance/), and why wouldn't it - Javascript is a web-first language after all.

If you're open to it, I might take a stab at this, and see if I can't come up with something that's sufficiently simple that it won't get in the way? I'm pretty sure I can actually make some of the code *simpler* than it is now, by avoiding the filesystem - while still keeping the templates.

If you're completely opposed, I won't spend time on it - I'll probably just use something else.

Let me know. 🙂

**Comment by jcoglan** [comment]
> What if the build step was fast and added very little complexity?

The sort of complexity I'm worried about here isn't about whether a certain build tool requires much configuration to work. As I see it, making this package work on the web would require:

- Either, compiling Handlebars templates to JS modules, or have a module that could supply their file content to the compiler at runtime on the web
- Using a bundler (webpack, parcel, esbuild, or something else) to package the project for the web
- Integrate these steps with the rest of the Make-driven build, which requires the tool to expose the module dependency tree; my experience is bundlers either don't do this or they're slow at it, which makes all your `make` tasks take longer
- Account for the fact that the project is self-hosting so we need "stable" and "work in progress" copies of the codebase present at all times

On top of this there's the ongoing maintenance cost of whatever bundler you're using changing how it works every so often -- either changing its interface, its configuration, its dependencies, its behaviour, and many other things. This is exactly what made it hard to ship this project for ages -- the build tools we were using became out of date and way too much effort to upgrade. This has been my usual experience with any JS project that I work on from time to time -- each time I come back to it I spend a big chunk of time just fixing the build again.

Canopy already has a slightly complicated build due to it being self-hosted and multi-language, and adding to this is only ever going to be a drain on my time. So unless there's a really big upside I'm reluctant to take that cost on. In this case I actively decided not to target the browser in order to make the project easier to work on, because I think it's a niche use case. It's possible that the project will one day be ported to another language entirely; it being currently written in JS should be seen as an incidental detail.

> This doesn't need to involve the file system - you already have logical filenames as part of your output model, so just make the CLI add the files to an input model as {name, content} pairs.

This can't be done if the pathnames are part of the input grammar and therefore not known in advance. The grammar parser would need to look up files on disk with names it got out of the input grammar, so you'd actually need an abstraction that resembled the filesystem API and some interface for the caller passing in an implementation of it so that any referenced grammars could be read out of it. This would add a lot of complexity to the implementation _and_ the UI.

> Keeping the filesystem out of the equation would support faster and simpler testing as well.

I know what you mean in general, but in this specific codebase the tests aren't coupled to the implementation at all -- they just run the executable to compile the example grammars to each target language. So faking out filesystem access, or using dependency injection, wouldn't make any difference, and the tests are plenty fast as it is; the JS, Ruby and Python tests run in about 200ms each.

On balance this would add a lot of cost and maintenance risk that I already spent a lot of effort to _remove_, so I'm not enthusiastic about reversing that work.

**Comment by mindplay-dk** [comment]
Handlebars [supports pre-compilation](https://handlebarsjs.com/api-reference/compilation.html#handlebars-precompile-template-options), so you could build the templates at `make` time, removing the need to read.

Add an entry-point `canopy/core` like many packages do, and have this return a string rather than writing to the filesystem.

These are small changes that don't add substantially to maintenance - it's implementation details, so you can keep the full round-trip testing approach with the CLI and maintain the same surface APIs, no breaking changes.

No need to bundle or change your build scripts, but it enables somebody else to bundle `canopy/core` for the web.

> This can't be done if the pathnames are part of the input grammar and therefore not known in advance.

Not sure what you mean. The templates files are just hard coded [templates](https://github.com/jcoglan/canopy/tree/main/templates), right? What's not known?

**Comment by jcoglan** [comment]
> No need to bundle or change your build scripts, but it enables somebody else to bundle canopy/core for the web.

It does however obligate me to make sure that the package _can_ be used on the web, which necessitates all the build complexity I've already mentioned, plus running CI on browsers. It's not essentially different from packaging the project for the web myself.

> > This can't be done if the pathnames are part of the input grammar and therefore not known in advance.
>
> Not sure what you mean. The templates files are just hard coded [templates](https://github.com/jcoglan/canopy/tree/main/templates), right? What's not known?

I'm not talking about the templates, I'm talking about planned future functionality where grammars can import one another under the user's control. That is you could write something like this in your grammar:

```
import grammar_foo from './path/to/grammar_foo.peg'
```

and then use `grammar_foo` or its rules inside the rules of the current grammar. This means the grammar parser needs to resolve pathnames and parse the grammars stored at those paths, to build a complete picture of the input grammar.

Supporting this on the web would require in injectable interface that can take a pathname and return the file content for that filename. If we assume this program only runs from a shell, we just use the `fs` and `path` modules. If we assume it runs on the web we have to invent an abstraction and write one implementation for node.js, and specify the interface so that web-based users can pass in their imported grammars. This adds a lot of complexity for a use case I'm not especially interested in supporting.

The gist of what I'm saying is that I already know how to do everything you're suggesting -- the problem isn't that I don't know how to do it. I _do_ know how to do what you're asking and I've deliberately moved the project away from that direction, because it was making maintenance too difficult.

**Comment by mindplay-dk** [comment]
I tried to set up a proper project with a boatload of web polyfills for Node dependencies.

https://github.com/mindplay-dk/canopy-web

For some reason, the `memfs` polyfill (for `fs`) comes out `undefined` when I bundle this.

Well, I give up. This package isn't intended to work on the web and that's that.
